version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      MSSQL_SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "11433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your_password123 -Q 'SELECT 1'",
        ]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - rdnet

  api:
    build:
      context: .
      dockerfile: RDTrackr-BackEnd/API/src/Backend/RDTrackR.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=RDTrackR;User=sa;Password=Your_password123;TrustServerCertificate=True;"
      DatabaseType: "SqlServer"
    networks:
      - rdnet

  frontend:
    build:
      context: ../frontend/RDTrackR-Frontend
      dockerfile: Dockerfile
    container_name: rdtrackr-frontend
    depends_on:
      - api
    ports:
      - "5173:80"
    networks:
      - rdnet

volumes:
  sql_data:

networks:
  rdnet:
    driver: bridge
