name: RDTrackR Backend - CI

on:
  push:
    branches: [ main, develop, master ]
  pull_request:
    branches: [ main, develop, master ]

env:
  DOTNET_VERSION: "8.0.x"

  PROJECT_PATH: RDTrackr/backend/RDTrackr-BackEnd/API
  API_PATH: RDTrackR/backend/RDTrackr-BackEnd/API/src/Backend/RDTrackR.API
  TESTS_PATH: RDTrackR/backend/RDTrackr-BackEnd/API/tests

jobs:

  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore & Test with Coverage
        working-directory: ${{ env.PROJECT_PATH }}
        run: |
          echo "➡️ Executando testes com cobertura..."
          dotnet test ${{ env.TESTS_PATH }} \
            --collect:"XPlat Code Coverage" \
            --results-directory ./TestResults

      - name: Debug coverage output
        working-directory: ${{ env.PROJECT_PATH }}
        run: |
          echo "== Procurando arquivos de cobertura =="
          find . -name "coverage.cobertura.xml" || echo "❌ Nenhum coverage encontrado"

      - name: Upload Coverage Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: ${{ env.PROJECT_PATH }}/**/coverage.cobertura.xml

  sonar-backend:
    runs-on: ubuntu-latest
    needs: backend-tests

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Coverage Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-coverage
          path: backend-coverage/

      - name: Debug Coverage Files
        run: |
          echo "== Arquivos de cobertura encontrados =="
          ls -R backend-coverage

      - name: SonarCloud Scan - Backend
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.organization=joaoadavid
            -Dsonar.projectKey=joaoadavid_rdtrackr-backend
            -Dsonar.sources=${{ env.API_PATH }}
            -Dsonar.cs.opencover.reportsPaths=backend-coverage/**/coverage.cobertura.xml
            -Dsonar.exclusions=**/frontend/**
