name: RDTrackR Frontend - CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  FRONT_PATH: RDTrackr/frontend/RDTrackR-Frontend

jobs:

  # =======================================
  # FRONTEND – TESTES + COVERAGE
  # =======================================
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: DEBUG — listar pastas
        run: |
          echo "== ROOT =="
          ls -R .

          echo "== FRONT_PATH =="
          ls -R ${{ env.FRONT_PATH }}

      - name: Install dependencies
        working-directory: ${{ env.FRONT_PATH }}
        run: npm ci

      - name: Run tests with coverage
        working-directory: ${{ env.FRONT_PATH }}
        run: npx vitest --run --coverage

      - uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: ${{ env.FRONT_PATH }}/coverage/


  # =======================================
  # FRONTEND – SONAR
  # =======================================
  sonar-frontend:
    runs-on: ubuntu-latest
    needs: test-frontend

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: frontend-coverage
          path: coverage/

      - name: SonarCloud Scan - Frontend
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.organization=joaoadavid
            -Dsonar.projectKey=joaoadavid_rdtrackr-frontend
            -Dsonar.sources=${{ env.FRONT_PATH }}/src
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
